### ISSUE TITLE
Create an endpoint to see build history

### ISSUE THREAD

**Issue by simonjaeger** [simonjaeger/dd2480-2#14]
Create an endpoint (e.g. /builds) to read the build history from disk and list it. Each build should also be available with a specific URL to see the build logs (e.g. /builds/f6bcf57). 

Can be worked on after #13.

Add URL to list all build in the README file.

**Comment by jagelid** [comment]
Each build URL can be accessed in the log files. CommitID is the suffix of the file name (e.g. /logs/log_f6bcf57).
