### ISSUE TITLE
Parse webhook and start the tasks

### ISSUE THREAD

**Issue by simonjaeger** [simonjaeger/dd2480-2#3]
Once the webhook is parsed, we can start the first task (pull repository) and initiate the work. See https://github.com/KTH-DD2480/smallest-java-ci/blob/master/ContinuousIntegrationServer.java for a reference.

**Comment by ALuper** [comment]
So if i understand correctly we want this part of the code (except returning target instead of printing?) as the first task that is executed?

 public void handle(String target,
                       Request baseRequest,
                       HttpServletRequest request,
                       HttpServletResponse response) 
        throws IOException, ServletException
    {
        response.setContentType("text/html;charset=utf-8");
        response.setStatus(HttpServletResponse.SC_OK);
        baseRequest.setHandled(true);

        System.out.println(target);

**Comment by simonjaeger** [comment]
@ALuper Yeah that is a great start! That way we start to listen to the port and will be able to catch the webhook from GitHub. We will however also need to look into the request and see the body of what is sent. It will tell us exactly what happened I assume (issue created, commit, etc.).

**Comment by ALuper** [comment]
But first we would have to set the server up to webhook from our github repository? or is this already achieved somewhere?

**Comment by simonjaeger** [comment]
@ALuper We will enter the URL of the server here in the settings of the repository. Then GitHub will start sending webhooks to the server. It's a bit tricky debug as you can imagine... But we don't have to do anything on the server for GitHub to start sending webhooks to us. 

Usually it's good if a program runs and responds with status code 200 because GitHub might stop sending us webhooks if we don't respond (but in that case we will just add it again in the settings).

The best way might be to get it running locally, and dig into the documentation to fake a webhook, send that to your program (using something like Fiddler, Postman, curl, etc.) and see if everything works accordingly. Then clone the repository on the server (using ssh) and start it, then we add the URL here in the settings of the repository and do something to trigger GitHub to send a webhook.

**Comment by simonjaeger** [comment]
To clarify: A webhook can be simplified as a HTTP request, but sent in the other way (server -> server). Usually you send your requests to a server, but in this context... GitHub will send us requests. It's a simple switch in the settings of the repository: "Hey GitHub, please notify this URL whenever something happens in the repository so that we can do something about it".

**Comment by ALuper** [comment]
Thanks for explaining! By faking webhooks do you mean for testing? I talked with another group that got suggested to them by the assistants to create a second, hello world type, repository that the CI worked on so you could test your server

**Comment by ALuper** [comment]
Alright, is the server available to the internet through ngrok or similar so that the webhooks from the test repo can be sent to it?

**Comment by simonjaeger** [comment]
@ALuper The server is available to the internet by itself. You can use ngrok if you want to expose your own computer. We don't need to as this is virtual machine in a data center. Not all the ports are open (see Slack), but we can open the ones we need. If you use the IP (pinned in Slack, 13.69.12.37), it is available. Try to ssh to it for instance.

**Comment by ALuper** [comment]
Ah so if I ssh in i can open a port for the webhooks to be sent to?

**Comment by simonjaeger** [comment]
@ALuper Yes there are two parts to this. It is also protected by the data center firewall (common for cloud servers), so I will unblock it there. And then you will have to ssh into it and open that port (using ufw or similar).
